category_lookup = {
    """Equity & Equity Related""": [
        """EQUITY & EQUITY RELATED""",
        """EQUITYEQUITYRELATED""",
        """Equity & Equity Related""",
        """Equity & Equity related""",
        """Equity & Equity related Aerospace & Defense""",
        """Equity & Equity related Automobiles""",
        """Equity & Equity related Banks""",
        """Equity & Equity related Biotechnology""",
        """Equity & Equity related Capital Markets""",
        """Equity & Equity related Construction""",
        """Equity & Equity related Consumer Durables""",
        """Equity & Equity related Electrical Equipment""",
        """Equity & Equity related Exchange Traded Funds""",
        """Equity & Equity related Finance""",
        """Equity & Equity related INVESTMENT FUNDS/MUTUAL FUNDS""",
        """Equity & Equity related IT - Software""",
        """Equity & Equity related Industrial Products""",
        """Equity & Equity related Pharmaceuticals & Biotechnology""",
        """Equity & Equity related Realty""",
        """Equity & Equity related Semiconductors""",
        """Equity Shares""",
        """Equity shares""",
        """FOREIGNEQUITYSECURITIES""",
        """Foreign Securities - Equity""",
        """CNX NIFTY-JUN - - -""",
    ],
    """Exchange Traded Funds (ETFs)""": [
        """ETF""",
        """Exchange Traded Funds""",
        """Exchange Traded Fund""",
        """Exchange Traded Funds Exchange Traded Funds""",
        """EXCHANGE TRADED FUND UNITS""",
        """International Exchange Traded Funds""",
        """International Exchange Traded Funds Exchange Traded Funds""",
        """FOREIGNETF""",
        """Foreign Securities and/or overseas ETF""",
        """Foreign Securities/Overseas ETFs""",
        """Nippon India ETF Gold Bees""",
    ],
    """Bonds & Debentures""": [
        """BOND & NCDs""",
        """BOND & NCDs ICRA A""",
        """BOND & NCDs Transport Infrastructure""",
        """Bonds""",
        """Central Government Securities""",
        """Government Dated Securities""",
        """Government Securities""",
        """Government Securities / SDL""",
        """Government Securities Central/State""",
        """Govt Security""",
        """State Government Securities""",
        """State Development Loan""",
        """Fixed rates bonds - Corporate""",
        """Zero Coupon Bonds""",
        """Zero Coupon Bond""",
        """Zero Coupon Bonds / Deep Discount Bonds""",
        """Convertible Debenture""",
        """Compulsory Convertible Debenture""",
        """COMPULSORILYCONVERTIBLEDEBENTURE""",
        """Debentures and Bonds""",
        """Debt Instruments""",
        """Debt Instruments SOVEREIGN""",
        """DEBT INSTRUMENTS""",
        """DEBTINSTRUMENTS""",
        """NON-CONVERTIBLE DEBENTURES/BONDS/ZCB""",
        """Non Convertible Debentures""",
        """Non Convertible Debentures / Bonds""",
        """NONCONVERTIBLEDEBENTURESBONDS""",
        """Securitised Debt""",
        """Securitized Debt Instruments""",
        """Securitized Debt""",
        """SECURITIZEDDEBTINSTRUMENTS""",
        """Corporate Debt Market Development Fund""",
        """Floating Rate Note""",
        """GOVERNMENT SECURITIES""",
        """GOVERNMENTSECURITIES""",
        """GOVERNMENTSECURITIESCENTRALSTATE""",
    ],
    """Money Market Instruments""": [
        """Certificate of Deposit""",
        """Certificate of Deposits""",
        """CD-Certificate of Deposits""",
        """Certificate of Deposit IND A""",
        """Certificate of Deposits C""",
        """Certificate of Deposits N""",
        """COMMERCIALPAPER""",
        """COMMERCIALPAPERSCP""",
        """COMMERCIAL PAPERS""",
        """Commercial Paper""",
        """Commercial Papers""",
        """Commercial Paper CP/Certificate of Deposits CD""",
        """Commercial Papers C""",
        """Commercial Paper PUBA""",
        """Certificate of Deposit Benchmark CRISIL Liquid Debt A-I Index""",
        """MONEY MARKET INSTRUMENTS""",
        """Treasury Bill""",
        """Treasury Bills""",
        """Treasury Bill/Cash Management Bill CRISIL A""",
        """Treasury Bill/Cash Management Bill SOVEREIGN""",
        """Treasury Bills T-Bil""",
        """Treasury Bill/Cash Management Bill""",
        """TREASURYBILLS""",
        """TREASURYBILL""",
        """Tri Party Repo TREPs""",
        """TREPS / Reverse Repo""",
        """Reverse Repo""",
        """Reverse Repo / TREPS""",
        """Reverse Repo --""",
        """Mutual Funds Cash & Equivalent""",
        """Government Securities Central/State Cash & Equivalent""",
    ],
    """Alternative Investments""": [
        """REIT""",
        """ReIT""",
        """Reits""",
        """Real Estate Investment Trust""",
        """Real Estate Investment Trusts""",
        """Units of Real Estate Investment Trust REITs""",
        """UNITS OF REIT""",
        """UNITSISSUEDBYREIT""",
        """BUNITSOFREALESTATEINVESTMENTTRUSTSREITS""",
        """Alternative Investment Fund""",
        """Alternative Investment Funds""",
        """Alternative Investment Funds AIF""",
        """Alternative Investment Fund Units""",
        """Units of an Alternative Investment Fund AIF""",
        """AIF CAT""",
        """ALTERNATIVEINVESTMENTFUND""",
        """ALTERNATIVEINVESTMENTFUNDUNITS""",
        """Alternative Investment FundsAIF""",
        """d Units of an Alternative Investment Fund AIF""",
        """Investment in AIF""",
        """CDMDFAIF""",
        """CMSI""",
        """InvIT""",
        """Invits""",
        """Units of Infrastructure Investment Trusts InvITs""",
        """UNITS OF INVIT""",
        """UNITSISSUEDBYINVIT""",
        """REIT/InvIT Instruments""",
    ],
    """Mutual Funds""": [
        """International Mutual Fund Units""",
        """Overseas Mutual Fund""",
        """Overseas Mutual Fund Units""",
        """Foreign Mutual Fund Units""",
        """Investment in Mutual Fund Units""",
        """Investment in Mutual fund""",
        """MUTUAL FUND UNITS""",
        """MUTUALFUNDUNITS""",
        """Mutual Fund Unit""",
        """Mutual Fund Units""",
        """Mutual Fund Units / Exchange Traded Funds""",
        """Mutual Funds""",
        """Margin Mutual Fund Units""",
    ],
    """Derivatives""": [
        """DERIVATIVES""",
        """DERIVATIVE""",
        """Futures""",
        """Option wise per unit Net Asset Values are as follows""",
        """Interest Rate Swaps""",
    ],
    """Commodities""": [
        """Gold""",
        """Silver""",
    ],
    """Other/Uncategorized""": [
        """Others""",
        """OTHERS""",
        """uncategorised""",
        """Privately Placed / Unlisted""",
        """Privately placed / Unlisted""",
        """Privately Placed/Unlisted""",
        """Privately Placed/unlisted""",
        """UNLISTED""",
        """BUNLISTED""",
        """Arbitrage""",
        """ISINCODE securityname Yield to Call""",
        """Numero Uno International Ltd Finance e-""",
        """RISKLEVELBASEDONPORTFOLIOASONMAY""",
        """RISKLEVELOFTIERBENCHMARKASONMAY""",
        """INEDMAFSRF Mahindra & Mahindra Financial Services Limited-Rights Share Finance""",
        """Investment - CCD""",
    ],
}
