"""Portfolio Post-Processor Module

This module defines the `PortfolioPostProcessor` class, responsible for
performing two main post-parsing operations:

1. Data Cleaning:
   - Reads intermediate `.cleaned` Excel files generated by individual parsers.
   - Standardizes numerical fields and scaling factors based on AMC configuration.
   - Filters invalid or redundant rows.
   - Outputs cleaned results into `.final_cleaned`.

2. Final Compilation:
   - Combines all `.final_cleaned` files.
   - Applies fuzzy mapping of investment categories to standardized labels.
   - Drops unnecessary columns and normalizes column order.
   - Exports a consolidated CSV file for downstream analytics.

The class is designed to be run after all AMC parsers complete execution.
"""

from asyncio import base_subprocess
from genericpath import exists
import os
import re
from tkinter.tix import COLUMN
import yaml
import logging
import pandas as pd
import numpy as np
from fuzzywuzzy import process

# -------------------------------------------------------------------
# Logger setup
# -------------------------------------------------------------------
logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s"
    )

# -------------------------------------------------------------------
# Class Definition
# -------------------------------------------------------------------
class PortfolioPostProcessor:
    """
    Unified class combining data cleaning and final compilation steps.

    Attributes:
        configs (dict): Parsed configuration from YAML file.
        output_folder (str): Directory containing pre-cleaned files (.cleaned).
        final_folder (str): Directory for saving cleaned results (.final_cleaned).
    """

    def __init__(self, config_path="./config/amc_configs.yaml"):
        """
        Initialize the post-processor by loading configuration
        and preparing output directories.

        Args:
            config_path (str): Path to the AMC configuration YAML file.
        """
        with open(config_path, "r") as f:
            self.configs = yaml.safe_load(f)
        default_config = self.configs.get("Defaults", {})
        self.path_bse_schemedata = default_config.get("path_BSE_SchemeData", 
                                                      r"reference\SchemeData0111251523SS.csv")
        if(not os.path.exists(self.path_bse_schemedata)):
            logger.error(f"Error Initializing PortfolioPostProcessor as BSE Scheme Data Path is invalid\n"+
                         f"{self.path_bse_schemedata}")
            print(f"Invalid Path BSE Scheme Data Table. {self.path_bse_schemedata}")
            exit(1)
        
        self.output_folder = ".cleaned"
        self.final_folder = ".final_cleaned"
        os.makedirs(self.output_folder, exist_ok=True)
        os.makedirs(self.final_folder, exist_ok=True)
        logger.info("Initialized PortfolioPostProcessor with configuration file loaded.")

    # -------------------------------------------------------------------
    # Step 1: Data Cleaning
    # -------------------------------------------------------------------
    def clean_data(self):
        """
        Clean each Excel file in `.cleaned` folder using numeric parsing
        and AMC-specific scaling factors. Save cleaned files to `.final_cleaned`.
        """

        # inline regex-based number extractors
        floatFilter = lambda x: re.findall(r"-?\d+\.\d+", str(x))
        integerFilter = lambda x: re.findall(r"-?\d+", str(x))

        def cleanString(s):
            """Convert strings with symbols and text into numeric values."""
            s = re.sub("%", "", str(s))
            try:
                return float(s)
            except Exception:
                pass
            s1 = floatFilter(s)
            if s1:
                return float(s1[0])
            s2 = integerFilter(s)
            if s2:
                return float(s2[0])
            return 0.0

        def dropCriteria(row):
            """
            Filter out rows where:
            - NAV % > 100.0
            - Both quantity and market value are zero
            """
            quantity, mkt, nav = row.iloc[4:7]
            return not ((nav > 100.0) or (quantity == 0 and mkt == 0))

        # -------------------------------------------------------------------
        # Iterate over all intermediate Excel outputs
        # -------------------------------------------------------------------
        files = [f for f in os.listdir(self.output_folder) if "~" not in f]
        logger.info(f"Starting data cleaning for {len(files)} files in {self.output_folder}")

        for filename in files:
            file_path = os.path.join(self.output_folder, filename)
            df = pd.read_excel(file_path)

            amc_name = df["AMC"].unique()[0]
            config = self.configs.get(amc_name, {})
            logger.info(f"Cleaning data for AMC: {amc_name}")

            # AMC-level scaling parameters
            scale_by_hundred = [s.lower() for s in config.get("Scale100", [])]
            factor_by_hundred = [s.lower() for s in config.get("Scale100th", [])]

            numeric_columns = [
                "coupon", "quantity", "market value (mkt) ( rs lakh )",
                "% to net assets (nav)", "yield", "yield to call (ytc)"
            ]

            # Clean and rescale numeric columns
            for col in numeric_columns:
                if col in df.columns:
                    df[col] = df[col].map(cleanString).astype(np.float64)
                    if col in factor_by_hundred:
                        df[col] = df[col] / 100
                    if col in scale_by_hundred:
                        df[col] = df[col] * 100
                    df[col] = df[col].fillna(0)

            # Standardize ISIN and yield columns
            df["isin"] = df["isin"].apply(lambda x: str(x)[:12])
            if "% to net assets (nav)" in df.columns:
                df["% to net assets (nav)"] = 100 * df["% to net assets (nav)"]
            if "yield" in df.columns:
                df["yield"] = 100 * df["yield"]
            if "yield to call (ytc)" in df.columns:
                df["yield to call (ytc)"] = 100 * df["yield to call (ytc)"]

            # Apply filter and write cleaned output
            df = df[df.apply(dropCriteria, axis=1)]
            df.to_excel(os.path.join(self.final_folder, filename), index=False)
            logger.info(f"Cleaned and saved file → {filename}")

    # -------------------------------------------------------------------
    # Step 2: Final Compilation
    # -------------------------------------------------------------------
    def compile_final_output(self):
        """
        Combine all cleaned files from `.final_cleaned` folder,
        apply fuzzy category mapping, and export consolidated CSV.
        """
        files = [f for f in os.listdir(self.final_folder) if "~" not in f]
        if not files:
            logger.warning("No cleaned files found to compile. Exiting.")
            return

        df = pd.concat(
            [pd.read_excel(os.path.join(self.final_folder, f)) for f in files],
            ignore_index=True
        )
        logger.info(f"Compiling {len(files)} cleaned workbooks into unified dataset")

        # -------------------------------------------------------------------
        # Category Mapping (domain classification of investment types)
        # -------------------------------------------------------------------       
        category_mapping = {
            # Equity & Equity Related
            'EQUITY & EQUITY RELATED': 'Equity & Equity Related',
            'Equity & Equity Related': 'Equity & Equity Related',
            'Equity & Equity related': 'Equity & Equity Related',
            'Equity & Equity Related Instruments': 'Equity & Equity Related',
            'Equity & Equity related Aerospace & Defense': 'Equity & Equity Related',
            'Equity & Equity related Automobiles': 'Equity & Equity Related',
            'Equity & Equity related Banks': 'Equity & Equity Related',
            'Equity & Equity related Biotechnology': 'Equity & Equity Related',
            'Equity & Equity related Capital Markets': 'Equity & Equity Related',
            'Equity & Equity related Construction': 'Equity & Equity Related',
            'Equity & Equity related Consumer Durables': 'Equity & Equity Related',
            'Equity & Equity related Electrical Equipment': 'Equity & Equity Related',
            'Equity & Equity related Exchange Traded Funds': 'Equity & Equity Related',
            'Equity & Equity related Finance': 'Equity & Equity Related',
            'Equity & Equity related IT - Software': 'Equity & Equity Related',
            'Equity & Equity related Industrial Products': 'Equity & Equity Related',
            'Equity & Equity related Pharmaceuticals & Biotechnology': 'Equity & Equity Related',
            'Equity & Equity related Realty': 'Equity & Equity Related',
            'Equity & Equity related Semiconductors': 'Equity & Equity Related',
            'Equity Shares': 'Equity & Equity Related',
            'Equity shares': 'Equity & Equity Related',
            'FOREIGNEQUITYSECURITIES': 'Equity & Equity Related',
            'Foreign Securities - Equity': 'Equity & Equity Related',
            'EQUITYEQUITYRELATED': 'Equity & Equity Related',

            # Exchange Traded Funds (ETFs)
            'Exchange Traded Fund': 'Exchange Traded Funds (ETFs)',
            'Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'EXCHANGE TRADED FUND UNITS': 'Exchange Traded Funds (ETFs)',
            'ETF': 'Exchange Traded Funds (ETFs)',
            'International Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'International Exchange Traded Funds Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'Foreign Securities and/or overseas ETF': 'Exchange Traded Funds (ETFs)',
            'Foreign Securities/Overseas ETFs': 'Exchange Traded Funds (ETFs)',
            'FOREIGNETF': 'Exchange Traded Funds (ETFs)',

            # Bonds & Debentures
            'BOND & NCDs': 'Bonds & Debentures',
            'Bonds': 'Bonds & Debentures',
            'Debentures and Bonds': 'Bonds & Debentures',
            'Zero Coupon Bond': 'Bonds & Debentures',
            'Zero Coupon Bonds': 'Bonds & Debentures',
            'Zero Coupon Bonds / Deep Discount Bonds': 'Bonds & Debentures',
            'Non Convertible Debentures': 'Bonds & Debentures',
            'Non Convertible Debentures / Bonds': 'Bonds & Debentures',
            'NON-CONVERTIBLE DEBENTURES/BONDS/ZCB': 'Bonds & Debentures',
            'II NON-CONVERTIBLE DEBENTURES/BONDS': 'Bonds & Debentures',
            'II NON-CONVERTIBLE DEBENTURES/BONDS/ZCB': 'Bonds & Debentures',
            'Convertible Debenture': 'Bonds & Debentures',
            'Compulsory Convertible Debenture': 'Bonds & Debentures',
            'COMPULSORILYCONVERTIBLEDEBENTURE': 'Bonds & Debentures',
            'Fixed rates bonds - Corporate': 'Bonds & Debentures',
            'Debt Instruments': 'Bonds & Debentures',
            'Debt Instruments SOVEREIGN': 'Bonds & Debentures',
            'DEBT INSTRUMENTS': 'Bonds & Debentures',
            'DEBTINSTRUMENTS': 'Bonds & Debentures',
            'Government Bonds': 'Bonds & Debentures',
            'Government Securities': 'Bonds & Debentures',
            'Government Securities / SDL': 'Bonds & Debentures',
            'Government Securities Central/State': 'Bonds & Debentures',
            'Government Securities Central/State Cash & Equivalent': 'Bonds & Debentures',
            'State Government Securities': 'Bonds & Debentures',
            'Govt Security': 'Bonds & Debentures',
            'Govt Securities / SDL': 'Bonds & Debentures',
            'Central Government Securities': 'Bonds & Debentures',
            'GOVERNMENT SECURITIES': 'Bonds & Debentures',
            'GOVERNMENTSECURITIES': 'Bonds & Debentures',
            'GOVERNMENTSECURITIESCENTRALSTATE': 'Bonds & Debentures',
            'i Government Securities': 'Bonds & Debentures',
            'ii State Government Securities': 'Bonds & Debentures',

            # Money Market Instruments
            'Certificate of Deposit': 'Money Market Instruments',
            'Certificate of Deposits': 'Money Market Instruments',
            'Certificate of Deposit IND A': 'Money Market Instruments',
            'Certificate of Deposits C': 'Money Market Instruments',
            'CERTIFICATEOFDEPOSIT': 'Money Market Instruments',
            'CERTIFICATEOFDEPOSITCD': 'Money Market Instruments',
            'CD-Certificate of Deposits': 'Money Market Instruments',
            'Commercial Paper': 'Money Market Instruments',
            'Commercial Papers': 'Money Market Instruments',
            'Commercial Papers C': 'Money Market Instruments',
            'COMMERCIALPAPER': 'Money Market Instruments',
            'COMMERCIALPAPERSCP': 'Money Market Instruments',
            'Treasury Bill': 'Money Market Instruments',
            'Treasury Bills': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill CRISIL A': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill SOVEREIGN': 'Money Market Instruments',
            'TREASURYBILL': 'Money Market Instruments',
            'TREASURYBILLS': 'Money Market Instruments',
            'T-Bil': 'Money Market Instruments',
            'Tri Party Repo TREPs': 'Money Market Instruments',
            'TREPS / Reverse Repo': 'Money Market Instruments',
            'Reverse Repo / TREPS': 'Money Market Instruments',
            'Reverse Repo --': 'Money Market Instruments',

            # Alternative Investments
            'Alternative Investment Fund': 'Alternative Investments',
            'Alternative Investment Fund Units': 'Alternative Investments',
            'Alternative Investment Funds': 'Alternative Investments',
            'Alternative Investment Funds AIF': 'Alternative Investments',
            'Units of an Alternative Investment Fund AIF': 'Alternative Investments',
            'Investment in AIF': 'Alternative Investments',
            'AIF CAT': 'Alternative Investments',
            'ALTERNATIVEINVESTMENTFUND': 'Alternative Investments',
            'ALTERNATIVEINVESTMENTFUNDUNITS': 'Alternative Investments',
            'CDMDFAIF': 'Alternative Investments',
            'Infrastructure Investment Trusts': 'Alternative Investments',
            'Units of Infrastructure Investment Trusts InvITs': 'Alternative Investments',
            'InvIT': 'Alternative Investments',
            'Invits': 'Alternative Investments',
            'Units issued by REITs & InvITs': 'Alternative Investments',
            'REIT': 'Alternative Investments',
            'Reits': 'Alternative Investments',
            'ReIT': 'Alternative Investments',
            'Units of Real Estate Investment Trust REITs': 'Alternative Investments',
            'Real Estate Investment Trusts': 'Alternative Investments',
            'Real Estate Investment Trust': 'Alternative Investments',
            'UNITS OF INVIT': 'Alternative Investments',
            'UNITS OF REIT': 'Alternative Investments',
            'UNITSISSUEDBYINVIT': 'Alternative Investments',
            'UNITSISSUEDBYREIT': 'Alternative Investments',
            'BUNITSOFREALESTATEINVESTMENTTRUSTSREITS': 'Alternative Investments',

            # Other/Uncategorized
            'Others': 'Other/Uncategorized',
            'OTHERS': 'Other/Uncategorized',
            'UNLISTED': 'Other/Uncategorized',
            'Unlisted': 'Other/Uncategorized',
            'Privately Placed / Unlisted': 'Other/Uncategorized',
            'Privately Placed/Unlisted': 'Other/Uncategorized',
            'Privately placed / Unlisted': 'Other/Uncategorized',
            'Option wise per unit Net Asset Values are as follows': 'Other/Uncategorized',
            'ISINCODE securityname Yield to Call': 'Other/Uncategorized',
            'Arbitrage': 'Other/Uncategorized',
            'Numero Uno International Ltd Finance e-': 'Other/Uncategorized',
            'Margin Mutual Fund Units': 'Other/Uncategorized',
            'RISKLEVELBASEDONPORTFOLIOASONMAY': 'Other/Uncategorized',
            'RISKLEVELOFTIERBENCHMARKASONMAY': 'Other/Uncategorized',
            'CMSI': 'Other/Uncategorized',
            'CNX NIFTY-JUN - - -': 'Other/Uncategorized',
            'Amount Rs in Lakhs to NAV': 'Other/Uncategorized',
            'uncategorised': 'Other/Uncategorized'
        }

        keys = list(category_mapping.keys())
        keys = [k.decode("utf-8", errors="ignore") if isinstance(k, bytes) else str(k) for k in keys]

        def fuzzy_map_entries_to_category(entries):
            """
            Perform fuzzy text matching to classify instrument types
            into standardized category labels.
            """
            results = {}
            for entry in entries:
                if not keys:
                    results[entry] = "others"
                else:
                    if isinstance(entry, bytes):
                        entry = entry.decode("utf-8", errors="ignore")
                    match, score = process.extractOne(str(entry), keys)
                    results[entry] = category_mapping.get(match, "others")
            return results

        # apply fuzzy category mapping to "Type" column
        if "Type" in df.columns:
            df["Type"] = df["Type"].map(
                fuzzy_map_entries_to_category(np.unique(df["Type"]))
            )

        # drop yield-to-call column if present
        if "yield to call (ytc)" in df.columns:
            df = df.drop("yield to call (ytc)", axis=1)

        # standardize final column names
        new_cols = [
            "Name of Instrument", "ISIN", "Coupon", "Industry", "Quantity",
            "Market Value", "% to Net Assets", "Yield", "Type",
            "Scheme Name", "AMC"
        ]
        if len(df.columns) == len(new_cols):
            df.columns = new_cols

        # join Scheme ISIN and Amfi Code
        df = self._join_bse_schemedata(df)

        # export final combined output
        df.to_csv(f"Portfolio_extracted_{pd.Timestamp.today().strftime('%d%m%y-%H%M')}.csv", index=False)
        logger.info("Final combined CSV successfully.")

    # -------------------------------------------------------------------
    # Step 3: Scheme ISIN and Amfi Code addition
    # -------------------------------------------------------------------
    def _join_bse_schemedata(self, portfolio_df: pd.DataFrame):
        def _standardize_scheme_name(scheme_name):
            patterns  =  ["- an.*","-an.*", r"\(an.*", r"\( an.*", r"\([^)]*\)", "as on.*", "scheme having.*"]
            scheme_name = str(scheme_name)
            scheme_name = scheme_name.lower()
            for pattern in patterns:
                scheme_name = re.sub(pattern, "", scheme_name)
            scheme_name = re.sub( r"[^a-z0-9\- ]", " ", scheme_name)
            scheme_name = re.sub(r"\s+"," ",scheme_name)

            return scheme_name.strip().lower()



        df = pd.read_csv(r"reference\SchemeData0111251523SS.csv")
        df["Scheme Name"]  = df["Scheme Name"].apply(_standardize_scheme_name)



        isin_pattern = r"[A-Z]{3}[A-Z0-9]{9}"
        additional_df = (
            portfolio_df.merge(
                df.astype(str).groupby("Scheme Name").agg({
                        "ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment": ", ".join,
                        "Code": ",".join
                    }).reset_index()
                    .assign(
                    **{
                        "ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment": 
                            lambda x: x["ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment"]
                                        .apply(lambda s: ",".join(re.findall(isin_pattern, s)))
                    }
                ),
                how = "left",
                left_on = portfolio_df["Scheme Name"].astype(str).apply(_standardize_scheme_name),
                right_on = "Scheme Name",
                suffixes=("","_df")
            )
            # .drop(columns=["Scheme Name_df"])
            .rename(columns = {"Code":"amfi_code",
                               "ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment":"isin_group"})
        )               

        return additional_df                                                                                                    
