 Defaults: &default
  OutputDirectory: &OutputDirecotry ./cleaned
  ISIN_File_Path: &default_isin_file_path ./ISIN/fundisin.xlsx
  final Columns: &default_columns
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry / Rating
  - Quantity
  - Market Value (MKT) ( rs lakh )
  - '% to Net Assets (NAV)'
  - Yield
  - Yield to call (YTC)
 
 360 One Asset Management:
  AMCName: 360 One Asset Management
  DataDirectory: ./data/data/360 One Asset Management
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Aditya Birla Sun Life Mutual Fund:
  AMCName: Aditya Birla Sun Life Mutual Fund
  DataDirectory: ./data/data/Aditya Birla Sun Life Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Axis Mutual Fund:
  AMCName: Axis Mutual Fund
  DataDirectory: ./data/data/Axis Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Bandhan Mutual Fund:
  AMCName: Bandhan Mutual Fund
  DataDirectory: ./data/data/Bandhan Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Bank of India Mutual Fund:
  AMCName: Bank of India Mutual Fund
  DataDirectory: ./data/data/Bank Of India Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Baroda BNP Paribas Mutual Fund:
  AMCName: Baroda BNP Paribas Mutual Fund
  DataDirectory: ./data/data/Baroda Bnp Paribas Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Canara Robeco Mutual Fund:
  AMCName: Canara Robeco Mutual Fund
  DataDirectory: ./data/data/Canara Robeco Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 DSP Mutual Fund:
  AMCName: DSP Mutual Fund
  DataDirectory: ./data/data/Dsp Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Edelweiss Mutual Fund:
  AMCName: Edelweiss Mutual Fund
  DataDirectory: ./data/data/Edelweiss Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Franklin Templeton India:
  AMCName: Franklin Templeton India
  DataDirectory: ./data/data/Franklin Templeton India
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Groww Mutual Fund:
  AMCName: Groww Mutual Fund
  DataDirectory: ./data/data/Groww Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - Yield
 HDFC Mutual Fund:
  AMCName: HDFC Mutual Fund
  DataDirectory: ./data/data/Hdfc Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
    - Yield
    - Yield to Call (YTC)
 Helios Mutual Fund:
  AMCName: Helios Mutual Fund
  DataDirectory: ./data/data/Helios Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 HSBC Mutual Fund:
  AMCName: HSBC Mutual Fund
  DataDirectory: ./data/data/Hsbc Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 ICICI Prudential Mutual Fund:
  AMCName: ICICI Prudential Mutual Fund
  DataDirectory: ./data/data/Icici Prudential Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - Yield to Call (YTC)
 Invesco Mutual Fund:
  AMCName: Invesco Mutual Fund
  DataDirectory: ./data/data/Invesco Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
 ITI Mutual Fund:
  AMCName: ITI Mutual Fund
  DataDirectory: ./data/data/Iti Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 JM Financial Mutual Fund:
  AMCName: JM Financial Mutual Fund
  DataDirectory: ./data/data/Jm Financial Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Kotak Mutual Fund:
  AMCName: Kotak Mutual Fund
  DataDirectory: ./data/data/Kotak Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
    - Yield
 LIC Mutual Fund:
  AMCName: LIC Mutual Fund
  DataDirectory: ./data/data/Lic Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Mahindra Manulife Mutual Fund:
  AMCName: Mahindra Manulife Mutual Fund
  DataDirectory: ./data/data/Mahindra Manulife Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Old Bridge Capital:
  AMCName: Old Bridge Capital
  DataDirectory: ./data/data/Old Bridge Capital
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
 Mirae Asset Mutual Fund:
  AMCName: Mirae Asset Mutual Fund
  DataDirectory: ./data/data/Mirae Asset Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Motilal Oswal Mutual Fund:
  AMCName: Motilal Oswal Mutual Fund
  DataDirectory: ./data/data/Motilal Oswal Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Navi Mutual Fund:
  AMCName: Navi Mutual Fund
  DataDirectory: ./data/data/Navi Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Nippon India Mutual Fund:
  AMCName: Nippon India Mutual Fund
  DataDirectory: ./data/data/Nippon India Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 NJ Mutual Fund:
  AMCName: NJ Mutual Fund
  DataDirectory: ./data/data/Nj Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 PGIM India Mutual Fund:
  AMCName: PGIM India Mutual Fund
  DataDirectory: ./data/data/Pgim India Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 PPFAS Mutual Fund:
  AMCName: PPFAS Mutual Fund
  DataDirectory: ./data/data/Ppfas Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Quant Mutual Fund:
  AMCName: Quant Mutual Fund
  DataDirectory: ./data/data/Quant Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
 Quantum Mutual Fund:
  AMCName: Quantum Mutual Fund
  DataDirectory: ./data/data/Quantum Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 SBI Mutual Fund:
  AMCName: SBI Mutual Fund
  DataDirectory: ./data/data/Sbi Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: 
    - '% to Net Assets (NAV)'
    - Yield to call (YTC)
 Shriram Mutual Fund:
  AMCName: Shriram Mutual Fund
  DataDirectory: ./data/data/Shriram Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Sundaram Mutual Fund:
  AMCName: Sundaram Mutual Fund
  DataDirectory: ./data/data/Sundaram Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Tata Mutual Fund:
  AMCName: Tata Mutual Fund
  DataDirectory: ./data/data/Tata Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Trust Mutual Fund:
  AMCName: Trust Mutual Fund
  DataDirectory: ./data/data/Trust Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Union Mutual Fund:
  AMCName: Union Mutual Fund
  DataDirectory: ./data/data/Union Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 UTI Mutual Fund:
  AMCName: UTI Mutual Fund
  DataDirectory: ./data/data/Uti Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 WhiteOak Mutual Fund:
  AMCName: WhiteOak Mutual Fund
  DataDirectory: ./data/data/Whiteoak Mutual Fund
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
 Zerodha Fund House:
  AMCName: Zerodha Fund House
  DataDirectory: ./data/data/Zerodha Fund House
  sheets_to_avoid: []
  final_columns: *default_columns
  Scale100: ""
  Scale100th: ""
