final_columns: &default_columns
  - Name of Instrument
  - ISIN
  - Coupon
  - Industry
  - Quantity
  - Market Value
  - '% to Net Assets'
  - Yield
  - Yield to call
  - Type
  - Scheme Name
  - AMC
  - Scheme ISIN
Axis Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/Axis Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/axis_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: Axis Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns: *default_columns
HDFC Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/HDFC Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/hdfc_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: HDFC Mutual Fund
  sheets_to_avoid: []
  column_mapping:
    ISIN: ISIN
    Coupon (%): Coupon
    Name Of the Instrument: Name of Instrument
    Industry+ /Rating: Industry
    Quantity: Quantity
    Market/ Fair Value (Rs. in Lacs.): Market Value
    '% to NAV': '% to Net Assets'
    Yield: Yield
    ~YTC (AT1/Tier 2 bonds): Yield to call
    Derivative % to NAV: Derivative % to NAV
    Unhedged % to NAV: Unhedged % to NAV
    final_columns: *default_columns
ICICI Prudential Mutual Fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/ICICI Prudential Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/icici_prudential_mutual_fund_portfolio.xlsx
  ISIN_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/ISIN/fundisin.xlsx
  amc_name: ICICI Prudential Mutual Fund
  sheets_to_avoid: []
  column_mapping:
    Company/Issuer/Instrument Name: Name of Instrument
    ISIN: ISIN
    Coupon: Coupon
    Industry/Rating: Industry
    Quantity: Quantity
    Exposure/Market Value(Rs.Lakh): Market Value
    '% to Nav': '% to Net Assets'
    Yield of the instrument: Yield
    Yield to Call @: Yield to call
  final_columns: *default_columns
kotak_mutual_fund:
  data_dir: /Users/njp60/Documents/code/mutualfundbackend/funddata/data/Kotak Mutual Fund
  output_file: /Users/njp60/Documents/code/AssetManagmentCompanyParser/output/kotak_mutual_fund_portfolio.xlsx
  amc_name: Kotak Mutual Fund
  sheets_to_avoid: []
  column_mapping: {}
  final_columns: *default_columns
